USE [bsDB]
GO

/****** Object:  Table [dbo].[BUSINESS]    Script Date: 1/5/2025 5:00:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUSINESS](
	[ID] [nvarchar](50) NOT NULL,
	[BUSINESS_NAME] [nvarchar](50) NOT NULL,
	[SHORT_NAME] [nvarchar](50) NULL,
	[OFFICE_ADDRESS] [nvarchar](50) NULL,
	[CONTACT_NAME] [nvarchar](50) NULL,
	[CONTACT_NO] [nvarchar](50) NULL,
	[EMAIL_ADDRESS] [nvarchar](50) NULL,
	[BIN] [nvarchar](50) NULL,
	[TAX_VAT_NO] [nvarchar](50) NULL,
	[BUSINESS_LOGO] [nvarchar](50) NULL,
	[COUNTRY_ID] [nvarchar](50) NULL,
	[CURRENCY_ID] [nvarchar](50) NULL,
	[MAX_EMPLOYEE] [int] NOT NULL,
	[MAX_SALARY] [int] NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CREATE_USER] [nvarchar](50) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_USER] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[REVISE_NO] [int] NOT NULL,
	[RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_BUSINESS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUSINESS] ADD  CONSTRAINT [DF_BUSINESS_MAX_EMPLOYEE]  DEFAULT ((1)) FOR [MAX_EMPLOYEE]
GO

ALTER TABLE [dbo].[BUSINESS] ADD  CONSTRAINT [DF_BUSINESS_MAX_SALARY]  DEFAULT ((1)) FOR [MAX_SALARY]
GO

ALTER TABLE [dbo].[BUSINESS] ADD  CONSTRAINT [DF_BUSINESS_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO

ALTER TABLE [dbo].[BUSINESS] ADD  CONSTRAINT [DF_BUSINESS_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [dbo].[BUSINESS] ADD  CONSTRAINT [DF_BUSINESS_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO

ALTER TABLE [dbo].[BUSINESS] ADD  CONSTRAINT [DF_BUSINESS_REVISE_NO]  DEFAULT ((1)) FOR [REVISE_NO]
GO


